const userWideSpecificStatusCode = {
  FAILED_SIGN_UP_INVALID_REQ_BODY: 4001,
  FAILED_SIGN_UP_USER_ALREADY_REGISTERED: 4002,

  FAILED_SIGN_IN_INVALID_REQ_BODY: 4101,
  FAILED_SIGN_IN_USER_NOT_REGISTERED: 4102,
  FAILED_SIGN_IN_INVALID_PASSWORD: 4103,
};

module.exports = {
  userWideSpecificStatusCode,
};
